### ISSUE TITLE
所有功能都在main.go中，希望分开

### ISSUE THREAD

**Issue by ZGarry** [ZGarry/go-web#4]

**Comment by ZGarry** [comment]
拆分架构的时候遇到一个问题：
1/拆分前确保了增删查改可以进行
2/拆分时，我希望把mysql连接作为一个单独的包，然后main包调用这个包的runMysql函数。
这个函数返回一个Db *sql对象。

但是之后再次对Db增删查改的时候，产生了错误：
![image](https://user-images.githubusercontent.com/43488431/71240076-31974680-2343-11ea-873e-b975d62a7317.png)

这似乎是一个关于锁的问题，目前我还在解决中。

**Comment by YouEclipse** [comment]
你把代码提交一下

**Comment by ZGarry** [comment]
https://stackoverflow.com/questions/36347015/go-variable-initialized-and-non-nil-but-nil-for-other-functions 这儿发现一个稍微相似的问题

**Comment by ZGarry** [comment]
> 你把代码提交一下

已经提交了

**Comment by ZGarry** [comment]
问题已解决：
：=默认左侧变量是局部变量。
如果左侧不是局部变量，将创建一个与外部全局变量相同名称的局部变量，并赋值
```go
var Db *sql.DB
func main() {
	Db,err := dbControl.RunMysql()
```
因而要将代码更改为这样
```go
```go
var Db *sql.DB
func main() {
	Db,err := dbControl.RunMysql()
```
```

**Comment by ZGarry** [comment]
错误的解决方向
1.以为是mysql链接问题
2.以为是函数传参问题
3.以为是指针问题

**Comment by ZGarry** [comment]
已完成
