### ISSUE TITLE
err处理的问题，请解决

### ISSUE THREAD

**Issue by ZGarry** [ZGarry/go-web#5]

**Comment by ZGarry** [comment]
![image](https://user-images.githubusercontent.com/43488431/71247562-f94c3400-2353-11ea-9895-a32861c9d19b.png)
如上图，每一个可能返回err的函数处都需要写一个return err（err的层层外传机制），这是合理的处理的err的范式么？

**Comment by YouEclipse** [comment]
是的 目前go里面的err都是这样处理.等go2吧:)
